In [1]:
import torch
from torch import nn

In [2]:
input_data = torch.tensor([[[[1.,2.],[3.,4.]]]])

### 1.Basic

In [26]:
# Create 2x2 input tensor
input_data = torch.tensor([[[[1.,2.],[3.,4.]]]])
# Create a TCL layer with kernel_size=3
transConv1 = nn.ConvTranspose2d(1, 1, 3, bias=False)
# Set kernel weights to be 1
transConv1.weight.data = torch.ones(1,1,3,3)
# Disable gradient decent
for w in transConv1.parameters():
    w.requires_grad = False
# Calculate the output
transConv1(input_data)

tensor([[[[ 1.,  3.,  3.,  2.],
          [ 4., 10., 10.,  6.],
          [ 4., 10., 10.,  6.],
          [ 3.,  7.,  7.,  4.]]]])

### 2.Stride

In [27]:
# Create a TCL layer with stride=2
transConv2 = nn.ConvTranspose2d(1, 1, 3, stride=2, bias=False)
# Set kernel weights to be 1
transConv2.weight.data = torch.ones(1,1,3,3)
# Disable gradient decent
for w in transConv2.parameters():
    w.requires_grad = False
# Calculate
transConv2(input_data)

tensor([[[[ 1.,  1.,  3.,  2.,  2.],
          [ 1.,  1.,  3.,  2.,  2.],
          [ 4.,  4., 10.,  6.,  6.],
          [ 3.,  3.,  7.,  4.,  4.],
          [ 3.,  3.,  7.,  4.,  4.]]]])

### 3.Padding

In [28]:
# Create a TCL layer with stride=2, padding=1
transConv3 = nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, bias=False)
# Set kernel weights to be 1
transConv3.weight.data = torch.ones(1,1,3,3)
# Disable gradient decent
for w in transConv3.parameters():
    w.requires_grad = False
# Calculate
transConv3(input_data)

tensor([[[[ 1.,  3.,  2.],
          [ 4., 10.,  6.],
          [ 3.,  7.,  4.]]]])

### 4.Output Padding

In [29]:
# Create a TCL layer with stride=2, output_padding=1
transConv4 = nn.ConvTranspose2d(1, 1, 3, stride=2, output_padding=1, bias=False)
# Set kernel weights to be 1
transConv4.weight.data = torch.ones(1,1,3,3)
# Disable gradient decent
for w in transConv4.parameters():
    w.requires_grad = False
# Calculate
transConv4(input_data)

tensor([[[[ 1.,  1.,  3.,  2.,  2.,  0.],
          [ 1.,  1.,  3.,  2.,  2.,  0.],
          [ 4.,  4., 10.,  6.,  6.,  0.],
          [ 3.,  3.,  7.,  4.,  4.,  0.],
          [ 3.,  3.,  7.,  4.,  4.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.]]]])

### 5.Dilation

In [30]:
# Create a TCL layer with kernel_size=2, stride=2, dilation=2
transConv5 = nn.ConvTranspose2d(1, 1, 2, stride=2, dilation=2, bias=False)
# Set kernel weights to be 1
transConv5.weight.data = torch.ones(1,1,2,2)
# Disable gradient decent
for w in transConv5.parameters():
    w.requires_grad = False
# Calculate
transConv5(input_data)

tensor([[[[ 1.,  0.,  3.,  0.,  2.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 4.,  0., 10.,  0.,  6.],
          [ 0.,  0.,  0.,  0.,  0.],
          [ 3.,  0.,  7.,  0.,  4.]]]])